import { CheckCircle2, Phone } from 'lucide-react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';
import ConversionCta from '../components/ConversionCta';

export type LocalPageData={city:string;nearby:string;context:string;issues:string[];localContext:string;inspection:string};
export default function LocalServicePage({data}:{data:LocalPageData}){return <div className="min-h-screen"><Header/><section className="bg-slate-900 py-20 text-center md:py-32"><div className="container mx-auto max-w-5xl px-6"><h1 className="mb-6 text-4xl font-bold !text-white md:text-6xl">Dryer Vent &amp; Air Duct Services in {data.city}, PA</h1><p className="mx-auto mb-8 max-w-3xl text-xl text-slate-200">{data.context}</p><a href="tel:+12157108781" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-8 py-4 font-semibold text-white"><Phone className="h-5 w-5"/>Call for Free Inspection</a></div></section>
<section className="bg-white py-20"><div className="container mx-auto max-w-7xl px-6"><div className="mb-10 text-center"><h2 className="mb-4 text-3xl font-bold text-slate-900 lg:text-4xl">Services Available in {data.city}</h2><p className="text-lg text-slate-700">Owner-operated service, no call center, no-pressure recommendations, and before-and-after proof when possible.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[['Dryer Vent Cleaning','/services/dryer-vent-cleaning'],['Dryer Vent Repair','/services/dryer-vent-repair'],['Dryer Vent Installation','/services/dryer-vent-installation'],['Air Duct Cleaning','/services/air-duct-cleaning']].map(([n,h])=><Link key={n} to={h} className="rounded-lg border border-slate-200 bg-slate-50 p-6 font-bold text-slate-900 hover:text-blue-600">{n}</Link>)}</div></div></section>
<section className="bg-slate-50 py-20"><div className="container mx-auto max-w-6xl px-6"><div className="grid gap-10 lg:grid-cols-2"><div><h2 className="mb-5 text-3xl font-bold text-slate-900">Common Local Service Needs</h2><ul className="space-y-4">{data.issues.map(i=><li key={i} className="flex gap-3 rounded-lg bg-white p-4"><CheckCircle2 className="h-5 w-5 flex-shrink-0 text-[#F97316]"/>{i}</li>)}</ul></div><div className="rounded-lg bg-slate-900 p-8"><h2 className="mb-5 text-3xl font-bold !text-white">Serving {data.city} and Nearby Communities</h2><p className="mb-6 text-slate-300">{data.nearby}</p><Link to="/free-inspection" className="font-semibold text-blue-400 underline">Request a free in-person inspection</Link></div></div></div></section>
<section className="bg-white py-20"><div className="container mx-auto max-w-6xl px-6"><div className="grid gap-8 lg:grid-cols-2"><article className="rounded-lg border border-slate-200 p-8"><h2 className="mb-4 text-2xl font-bold text-slate-900">What We Commonly See Around {data.city}</h2><p className="text-lg leading-relaxed text-slate-700">{data.localContext}</p></article><article className="rounded-lg border border-slate-200 p-8"><h2 className="mb-4 text-2xl font-bold text-slate-900">Inspection Before Recommendation</h2><p className="text-lg leading-relaxed text-slate-700">{data.inspection}</p></article></div></div></section>
<ConversionCta title={`Need Service in ${data.city}?`} description={`Request a free in-person inspection in ${data.city}. You receive a clear scope and price before work begins.`} onlineLabel={`Check Availability in ${data.city}`} /><Footer/></div>}
