import { MapPin, Phone } from 'lucide-react';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';
import CompletedJobsMap from '../components/CompletedJobsMap';

const bucks = ['Jamison','Doylestown','Newtown','Richboro','Warrington','Yardley','New Hope','Warminster','Chalfont','Southampton','Langhorne','Quakertown'];
const montgomery = ['Lansdale','Blue Bell','North Wales','Montgomeryville','Ambler','Horsham','Willow Grove','Hatboro','Plymouth Meeting','Collegeville'];
const services = [['Dryer Vent Cleaning','/services/dryer-vent-cleaning'],['Dryer Vent Repair','/services/dryer-vent-repair'],['Dryer Vent Installation','/services/dryer-vent-installation'],['Air Duct Cleaning','/services/air-duct-cleaning'],['Air Duct Repair','/services/air-duct-repair'],['Air Duct Installation','/services/air-duct-installation']];
const localPages = [['Doylestown','/doylestown-pa'],['Newtown','/newtown-pa'],['Richboro','/richboro-pa'],['Warrington','/warrington-pa']];

export default function ServiceAreaPage(){return <div className="min-h-screen"><Header/><section className="bg-slate-900 py-20 text-center md:py-32"><div className="container mx-auto max-w-5xl px-6"><MapPin className="mx-auto mb-6 h-12 w-12 text-[#F97316]"/><h1 className="mb-6 text-4xl font-bold !text-white md:text-6xl">Dryer Vent &amp; Air Duct Services in Bucks County and Montgomery County</h1><p className="mx-auto mb-8 max-w-3xl text-xl text-slate-200">Air Duct Priority is an owner-operated company based in Jamison, Pennsylvania, providing cleaning, repair, installation, and free in-person inspections throughout the local area.</p><a href="tel:+12157108781" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-8 py-4 font-semibold text-white"><Phone className="h-5 w-5"/>Call for Free Inspection</a></div></section>
<section className="bg-white py-20"><div className="container mx-auto max-w-7xl px-6"><div className="grid gap-8 md:grid-cols-2"><Area title="Bucks County" cities={bucks}/><Area title="Montgomery County" cities={montgomery}/></div></div></section>
<section className="bg-slate-900 py-20"><div className="container mx-auto max-w-6xl px-6"><div className="grid gap-8 lg:grid-cols-2"><article className="rounded-lg border border-slate-700 bg-slate-800 p-8"><h2 className="mb-4 text-2xl font-bold !text-white">Real Local Service Coverage</h2><p className="text-lg leading-relaxed text-slate-300">These communities reflect the area where Air Duct Priority regularly performs inspections, dryer vent cleaning and repair, duct cleaning, and installation work. Availability depends on the job scope, access, and schedule, so nearby homeowners can call to confirm service.</p></article><article className="rounded-lg border border-slate-700 bg-slate-800 p-8"><h2 className="mb-4 text-2xl font-bold !text-white">Based in Jamison, Pennsylvania</h2><p className="text-lg leading-relaxed text-slate-300">The company is owner-operated and serves homes across Central and Lower Bucks County, nearby Montgomery County communities, and surrounding areas without using a generic national call center.</p></article></div></div></section>
<CompletedJobsMap />
<section className="bg-slate-50 py-20"><div className="container mx-auto max-w-7xl px-6"><div className="mb-10 text-center"><h2 className="mb-4 text-3xl font-bold text-slate-900 lg:text-4xl">Services Available Across the Area</h2><p className="text-lg text-slate-700">Inspection-first recommendations, clear pricing, and before-and-after proof when possible.</p></div><div className="grid gap-4 md:grid-cols-3">{services.map(([name,href])=><Link key={name} to={href} className="rounded-lg border border-slate-200 bg-white p-6 font-bold text-slate-900 shadow-sm hover:text-blue-600">{name}</Link>)}</div></div></section>
<section className="bg-white py-20"><div className="container mx-auto max-w-6xl px-6"><h2 className="mb-8 text-center text-3xl font-bold text-slate-900 lg:text-4xl">Local Service Guides</h2><div className="grid gap-5 md:grid-cols-4">{localPages.map(([name,href])=><Link key={name} to={href} className="rounded-lg border-l-4 border-[#F97316] bg-slate-50 p-6 font-bold text-slate-900 hover:text-blue-600">{name}, PA</Link>)}</div><div className="mt-12 text-center"><p className="mb-6 text-lg text-slate-700">Do not see your town listed? Call to confirm availability for your address and service need.</p><a href="tel:+12157108781" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-8 py-4 font-semibold text-white"><Phone className="h-5 w-5"/>Call (215) 710-8781</a></div></div></section><Footer/></div>}
function Area({title,cities}:{title:string,cities:string[]}){return <div className="rounded-lg border border-slate-200 bg-slate-50 p-8"><h2 className="mb-6 text-2xl font-bold text-slate-900">{title}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{cities.map(c=><div key={c} className="rounded bg-white p-3 text-center text-sm font-semibold text-slate-700">{c}, PA</div>)}</div></div>}
